info:
  app:
    name: ${SPRING_APPLICATION_NAME}
    description: "Microservices-based backend system for E-Commerce Online Shop - ${spring.application.name} Service"
    version: "1.0.0"

management:
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${SPRING_APPLICATION_NAME}

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_SERVER_PORT:8080}/eureka