services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: ecommerce-rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  productsdb:
    container_name: products-db
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: products
    extends:
      file: common-config.yml
      service: microservice-db-config

  ordersdb:
    container_name: orders-db
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: orders
    extends:
      file: common-config.yml
      service: microservice-db-config

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      timeout: 10s
      retries: 5
    networks:
      - ecommerce

  configservice:
    image: "timebetov/config-service"
    container_name: config-service-ms
    ports:
      - "8070:8070"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      SERVER_PORT: 8070
      SPRING_APPLICATION_NAME: "configservice"
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: ${GIT_CONFIG_URI}
      CRYPTO_KEY: ${CRYPTO_KEY}
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  discoveryservice:
    image: "timebetov/eureka-service"
    container_name: discovery-service-ms
    ports:
      - "8071:8071"
    depends_on:
      configservice:
        condition: service_healthy
    environment:
      SERVER_PORT: 8071
      SPRING_APPLICATION_NAME: "eurekaservice"
    healthcheck:
      test: "curl --fail -silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configservice-config

  productservice:
    image: "timebetov/products-service"
    container_name: products-ms
    ports:
      - "8084:8084"
    depends_on:
      productsdb:
        condition: service_healthy
      discoveryservice:
        condition: service_healthy
    environment:
      SERVER_PORT: 8084
      SPRING_APPLICATION_NAME: "products"
      SPRING_DATASOURCE_URL: "jdbc:mysql://productsdb:3306/products"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  orderservice:
    image: "timebetov/orders-service"
    container_name: orders-ms
    ports:
      - "8081:8081"
    depends_on:
      ordersdb:
        condition: service_healthy
      discoveryservice:
        condition: service_healthy
    environment:
      SERVER_PORT: 8081
      SPRING_APPLICATION_NAME: "orders"
      SPRING_DATASOURCE_URL: "jdbc:mysql://ordersdb:3306/orders"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  identityservice:
    image: "timebetov/identity-service"
    container_name: identity-ms
    ports:
      - "8082:8082"
    depends_on:
      discoveryservice:
        condition: service_healthy
    environment:
      SERVER_PORT: 8082
      SPRING_APPLICATION_NAME: "identity"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  basketservice:
    image: "timebetov/basket-service"
    container_name: basket-ms
    ports:
      - "8083:8083"
    depends_on:
      discoveryservice:
        condition: service_healthy
    environment:
      SERVER_PORT: 8083
      SPRING_APPLICATION_NAME: "basket"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  gatewayservice:
    image: "timebetov/gateway-service"
    container_name: gateway-ms
    ports:
      - "8080:8080"
    depends_on:
      - productservice
      - ordersdb
      - identityservice
      - basketservice
    environment:
      SERVER_PORT: 8080
      SPRING_APPLICATION_NAME: "gatewayservice"
      REDIS_HOST: redis
      MANAGEMENT_INFO_ENV_ENABLED: "true"
      MANAGEMENT_ENDPOINT_GATEWAY_ACCESS: unrestricted
      EUREKA_HOST: discoveryservice
      EUREKA_SERVER_PORT: 8071
    extends:
      file: common-config.yml
      service: microservice-configservice-config

networks:
  ecommerce:
    driver: bridge