spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_URI}
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lowerCaseServiceId: true
          httpclient:
            connect-timeout: 1000
            response-timeout: 2s
  data:
    redis:
      connect-timeout: 2s
      host: ${REDIS_HOST:localhost}
      port: 6379
      timeout: 1s

management:
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${SPRING_APPLICATION_NAME}

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_SERVER_PORT:8080}/eureka

info:
  app:
    name: ${SPRING_APPLICATION_NAME}
    description: Microservices-based backend system for E-Commerce Online Shop - ${SPRING_APPLICATION_NAME} Service
    version: "1.0.0"

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000