spring:
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

management:
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: ${CRYPTO_KEY:45D81EC1EF61DF9AD8D3E5BB397F9}

logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}